plugins { id 'com.android.application' }

android { namespace 'com.sergi.glyphcomposite'; compileSdk 35
    defaultConfig { applicationId 'com.sergi.glyphcomposite'; minSdk 34; targetSdk 35; versionCode 1; versionName '1.0' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar'])
    implementation 'androidx.core:core:1.15.0'
}
